[package]
name = "embassy-wireguard"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
boringtun = { git = "https://github.com/SimonIT/boringtun.git", branch = "no_std", default-features = false, features = [
  "alloc",
] }
defmt = { version = "1.1.1", optional = true }
embassy-futures = "0.1.2"
embassy-net = { version = "0.9.1", features = [
  "dhcpv4",
  "medium-ethernet",
  "medium-ip",
  "udp",
] }
embassy-net-driver-channel = "0.3.2"
embassy-time = "0.5.1"
smoltcp = { version = "0.13.1", default-features = false, features = [
  "async",
  "medium-ip",
  "socket",
  "socket-udp",
] }

[features]
default = ["proto-ipv4", "proto-ipv6"]
proto-ipv4 = ["embassy-net/proto-ipv4", "smoltcp/proto-ipv4"]
proto-ipv6 = ["embassy-net/proto-ipv6", "smoltcp/proto-ipv6"]
defmt = [
  "dep:defmt",
  "boringtun/defmt",
  "embassy-futures/defmt",
  "embassy-net-driver-channel/defmt",
  "embassy-net/defmt",
  "embassy-time/defmt",
  "smoltcp/defmt",
]

[patch.crates-io]
# boringtun
ip_network = { git = "https://github.com/SimonIT/ip_network.git", branch = "no_std" }
ip_network_table = { git = "https://github.com/SimonIT/ip_network_table.git", branch = "no_std" }
ip_network_table-deps-treebitmap = { git = "https://github.com/SimonIT/treebitmap.git", branch = "fix-alloc" }
ring = { git = "https://github.com/SimonIT/ring.git", branch = "ariel-os" }
